#!/bin/bash

#######################################################################
#       journalcheck - Something like 'logcheck' for journald         #
#                      2015 - Alexander Koch                          #
#######################################################################

#######################################################################
#  This piece of software is released under MIT License, see LICENSE  #
#  file.                                                              #
#######################################################################


FILTER_GLOBAL=${FILTER_GLOBAL:-"/usr/share/journalcheck.d"}
FILTER_LOCAL=${FILTER_LOCAL:-"$HOME/.journalcheck.d"}
MERGE_FILE=${MERGE_FILE:-"/tmp/merged.ignore"}
STATE_FILE=${STATE_FILE:-"/var/tmp/journalcheck.state"}


cat "$FILTER_GLOBAL"/*.ignore > "$MERGE_FILE"
if [ -d "$FILTER_LOCAL" ]; then
	for F in "$FILTER_LOCAL"/*.ignore; do
		cat "$F" >> "$MERGE_FILE"
	done
fi

if [ -r "$STATE_FILE" ]; then
	journalctl --no-pager -a --since="$(cat "$STATE_FILE")" | egrep -vf "$MERGE_FILE"
else
	journalctl --no-pager -a | egrep -vf "$MERGE_FILE"
fi

date +'%F %T' > "$STATE_FILE"
rm -f "$MERGE_FILE"

exit 0
